version: '2'

services:
  mastodon-db:
    image: 'postgres:15.1-alpine'
    volumes:
      - './db:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: '${MASTODON_POSTGRES_DATABASE}'
      POSTGRES_USER: '${MASTODON_POSTGRES_USERNAME}'
      POSTGRES_PASSWORD: '${MASTODON_POSTGRES_PASSWORD}'
    networks:
      - mastodon_backend

  mastodon-redis:
    image: 'redis:7.0-alpine'
    networks:
      - mastodon_backend

  mastodon-web:
    image: 'tootsuite/mastodon:v4.0'
    command: 'bash -c "/provision.sh; rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"'
    volumes:
      - './web:/mastodon/public/system'
      - './provision.sh:/provision.sh:ro'
    environment:
      RAILS_ENV: 'production'
      LOCAL_DOMAIN: '${MASTODON_DOMAIN}'
      REDIS_HOST: 'mastodon-redis'
      DB_HOST: 'mastodon-db'
      DB_NAME: '${MASTODON_POSTGRES_DATABASE}'
      DB_USER: '${MASTODON_POSTGRES_USERNAME}'
      DB_PASS: '${MASTODON_POSTGRES_PASSWORD}'
      SECRET_KEY_BASE: '${MASTODON_SECRET_KEY_BASE}'
      OTP_SECRET: '${MASTODON_OTP_SECRET}'
    networks:
      - mastodon_backend
      - proxy
    depends_on:
      - mastodon-db
      - mastodon-redis
               
networks:
  mastodon_backend:
  proxy:
    external: true


